// Static seed recipes — Phase 1 offline fallback.
// Phase 2 replaces this with live Supabase data; keep this file as offline safety net.

export const RECIPES = [
  {
    id: 'r1',
    author: 'James Hoffmann',
    author_tier: 'guru',
    is_official: true,
    bean_name: 'Ethiopian Yirgacheffe',
    bean_origin: 'Ethiopia',
    bean_roast: 'Light',
    method: 'V60',
    parameters: { dose: 15, yield: 250, time: '3:00', grind: 20, grind_device: 'Comandante C40', temp: 93 },
    notes: 'Bloom 45s with 50g. Slow, even pour in two stages. Expect bright citrus and jasmine.',
    affiliate_links: [],
    rating_count: 142,
  },
  {
    id: 'r2',
    author: 'Scott Rao',
    author_tier: 'guru',
    is_official: true,
    bean_name: 'Colombian Huila Washed',
    bean_origin: 'Colombia',
    bean_roast: 'Medium-Light',
    method: 'Espresso',
    parameters: { dose: 18, yield: 36, time: '28', grind: 12, grind_device: 'Niche Zero', temp: 92 },
    notes: '1:2 ratio. Pull at 9 bar. Expect caramel sweetness with a clean, lingering finish.',
    affiliate_links: [],
    rating_count: 98,
  },
  {
    id: 'r3',
    author: 'Onyx Coffee Lab',
    author_tier: 'retailer',
    is_official: true,
    bean_name: 'Geometry Espresso Blend',
    bean_origin: 'Guatemala / Ethiopia',
    bean_roast: 'Medium',
    method: 'Espresso',
    parameters: { dose: 19, yield: 40, time: '30', grind: 14, grind_device: 'EK43S', temp: 93 },
    notes: 'Designed for milk drinks. Rich chocolate base with red fruit clarity on top.',
    affiliate_links: [],
    rating_count: 67,
  },
  {
    id: 'r4',
    author: 'Fellow',
    author_tier: 'retailer',
    is_official: true,
    bean_name: 'Brazilian Natural',
    bean_origin: 'Brazil',
    bean_roast: 'Medium-Dark',
    method: 'AeroPress',
    parameters: { dose: 17, yield: 200, time: '2:00', grind: 16, grind_device: 'Timemore C3', temp: 85 },
    notes: 'Inverted method. Dark chocolate and peanut butter. Forgiving on grind — great for travel.',
    affiliate_links: [],
    rating_count: 54,
  },
  {
    id: 'r5',
    author: 'Kaffa',
    author_tier: 'grower',
    is_official: true,
    bean_name: 'Jimma Natural Process',
    bean_origin: 'Ethiopia',
    bean_roast: 'Light',
    method: 'French Press',
    parameters: { dose: 30, yield: 500, time: '4:00', grind: 28, grind_device: 'Baratza Encore', temp: 94 },
    notes: 'Coarse grind is key. Full plunge at 4 min. Blueberry jam and wine notes — polarizing, people love or hate it.',
    affiliate_links: [],
    rating_count: 31,
  },
];

export const TIER_LABELS = {
  guru:     '☕ Guru',
  grower:   '🌱 Grower',
  retailer: '🏪 Retailer',
  user:     '',
};
